language: node_js
dist: trusty
node_js:
  - "4.4"
  - "0.10"
  - "0.11"
  - "0.12"
  - iojs
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8